# Generated by Django 4.2.3 on 2023-08-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='workInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(blank=True)),
                ('project_site', models.TextField(blank=True)),
                ('sub_contractor', models.TextField(blank=True)),
                ('first_name', models.TextField(blank=True)),
                ('middle_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('work_start_time', models.DateField(default=None)),
                ('bag_check_done_on_entry', models.BooleanField(default=False)),
                ('fit_to_work_physical_health', models.BooleanField(default=False)),
                ('fit_to_work_mind', models.BooleanField(default=False)),
                ('dressed_properly', models.BooleanField(default=False)),
                ('meeting_site_safety_requirements', models.BooleanField(default=False)),
                ('work_end_time', models.DateField(default=None)),
                ('bag_check_done_on_exit', models.BooleanField(default=False)),
                ('safety_shoes', models.BooleanField(default=False)),
                ('safety_jacket', models.BooleanField(default=False)),
                ('safety_helmet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
