# Generated by Django 4.2.3 on 2023-08-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_picture_workinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
