# Generated by Django 4.2.3 on 2023-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinformation',
            name='id',
        ),
        migrations.AddField(
            model_name='workinformation',
            name='auto_increment_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
