# Generated by Django 4.2.3 on 2023-08-04 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_workinformation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinformation',
            name='auto_increment_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
