# Generated by Django 4.2.3 on 2023-08-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_workinformation_auto_increment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinformation',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
