# Generated by Django 4.2.3 on 2023-08-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_profile_picture_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bag_chack_done_on_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bag_check_done_on_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='dressed_properly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fir_to_work_mind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fit_to_work_physical_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meeting_site_safety_requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='project_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='project_site',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='safety_helmet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='safety_jacket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='safety_shoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_contractor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_end_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='work_start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
