# Generated by Django 4.2.3 on 2023-08-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workinformation_auto_increment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinformation',
            name='auto_increment_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
