# Generated by Django 4.2.3 on 2023-08-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workinformation_auto_increment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('project_name', models.TextField(blank=True)),
                ('project_location', models.TextField(blank=True)),
                ('supervisor_name', models.TextField(blank=True)),
                ('subcontractor_name', models.TextField(blank=True)),
                ('work_start_date', models.DateField(default=None)),
                ('work_completion_date', models.DateField(default=None)),
                ('wcp_esic_verification_status', models.TextField(blank=True)),
                ('wcp_esic_verification', models.TextField(blank=True)),
                ('before_entry_body_scanning_status', models.TextField(blank=True)),
                ('before_entry_body_scanning', models.TextField(blank=True)),
                ('before_entry_bag_check_status', models.TextField(blank=True)),
                ('before_entry_bag_check', models.BooleanField(default=False)),
                ('physical_appearance_status', models.TextField(blank=True)),
                ('physical_appearance', models.TextField(blank=True)),
                ('before_entry_bag_tales_and_tool_check_status', models.TextField(blank=True)),
                ('before_entry_bag_tales_and_tool_check', models.TextField(blank=True)),
                ('before_entry_bag_mental_health_check_status', models.TextField(blank=True)),
                ('before_entry_bag_mental_health_check', models.TextField(blank=True)),
                ('physical_health_check_status', models.TextField(blank=True)),
                ('physical_health_check', models.TextField(blank=True)),
                ('before_entry_bag_behavioral_check_status', models.TextField(blank=True)),
                ('before_entry_bag_behavioral_check', models.TextField(blank=True)),
                ('before_entry_bag_safety_helmet_check_status', models.TextField(blank=True)),
                ('before_entry_bag_safety_helmet_check', models.TextField(blank=True)),
                ('before_entry_bag_safety_shoes_check_status', models.TextField(blank=True)),
                ('before_entry_bag_safety_shoes_check', models.TextField(blank=True)),
                ('before_entry_bag_safety_jackets_check_status', models.TextField(blank=True)),
                ('before_entry_bag_safety_jackets_check', models.TextField(blank=True)),
                ('ladders_health_check_status', models.TextField(blank=True)),
                ('ladders_health_check', models.TextField(blank=True)),
                ('work_place_check_status', models.TextField(blank=True)),
                ('work_place_check', models.TextField(blank=True)),
                ('work_place_cleanliness_check_status', models.TextField(blank=True)),
                ('work_place_cleanliness_check', models.TextField(blank=True)),
                ('balance_material_on_specified_area_check_status', models.TextField(blank=True)),
                ('balance_material_on_specified_area_check', models.TextField(blank=True)),
                ('ladders_placement_check_status', models.TextField(blank=True)),
                ('ladders_placement_check', models.TextField(blank=True)),
                ('before_exit_body_scanning_status', models.TextField(blank=True)),
                ('before_exit_body_scanning', models.TextField(blank=True)),
                ('before_exit_bag_check_status', models.TextField(blank=True)),
                ('before_exit_bag_check', models.BooleanField(default=False)),
                ('before_exit_bag_tales_and_tool_check_status', models.TextField(blank=True)),
                ('before_exit_bag_tales_and_tool_check', models.TextField(blank=True)),
                ('before_exit_bag_mental_health_check_status', models.TextField(blank=True)),
                ('before_exit_bag_mental_health_check', models.TextField(blank=True)),
                ('before_exit_bag_behavioral_check_status', models.TextField(blank=True)),
                ('before_exit_bag_behavioral_check', models.TextField(blank=True)),
                ('before_exit_bag_safety_helmet_check_status', models.TextField(blank=True)),
                ('before_exit_bag_safety_helmet_check', models.TextField(blank=True)),
                ('before_exit_bag_safety_shoes_check_status', models.TextField(blank=True)),
                ('before_exit_bag_safety_shoes_check', models.TextField(blank=True)),
                ('before_exit_bag_safety_jackets_check_status', models.TextField(blank=True)),
                ('before_exit_bag_safety_jackets_check', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_increment_id', models.AutoField(default=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='workInformation',
        ),
    ]
