# Generated by Django 4.2.3 on 2023-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_checklist_delete_workinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='before_entry_bag_check',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='before_exit_bag_check',
            field=models.TextField(blank=True),
        ),
    ]
