# Generated by Django 4.2.3 on 2023-08-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_work_end_time_alter_user_work_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bag_chack_done_on_entry',
            new_name='bag_check_done_on_entry',
        ),
    ]
