# Generated by Django 4.2.3 on 2023-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_checklist_aadhar_card_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='aadhar_card_verification',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='aadhar_card_verification_status',
            field=models.TextField(blank=True, default=None),
        ),
    ]
