# Generated by Django 4.2.3 on 2023-08-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_bag_chack_done_on_entry_user_bag_check_done_on_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fir_to_work_mind',
            new_name='fit_to_work_mind',
        ),
    ]
