# Generated by Django 4.2.3 on 2023-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_checklist_aadhar_card_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='project_location1',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='project_name1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='work_completion_date1',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='work_start_date1',
            field=models.DateField(default=None),
        ),
    ]
